// Code generated by github.com/wanjm/gos DO NOT EDIT.
import 'package:component_set/component_set.dart';
import 'package:component_generator/component_generator.dart';
import 'schema.gen.dart';
import 'myclient.dart';

part 'network.gen.g.dart';

@DataInterface()
abstract class SimpleBiz {
  /// hello函数标题
  static const String sayHelloUrl = "/hello";
  /// hello函数标题
  @ReqConfig(sayHelloUrl)
  Future<RespData<HelloResponse?>> sayHello(HelloRequest data);
}

