// Code generated by github.com/wanjm/gos DO NOT EDIT.
import 'package:component_set/component_set.dart';

// ["name"]
class HelloRequest extends JSONParameter {
 /// 招呼名字
 String name;

  HelloRequest({
  this.name = "",

  });

  factory HelloRequest.fromJson(Map<String, dynamic> json) {
    return HelloRequest(
   name: json['name'] as String? ?? "",
    );
  }

  @override
  Map<String, dynamic> toJson() {
    return {
      "name": name,
    };
  }
}

// ["message"]
class HelloResponse extends JSONParameter {
 /// 招呼内容
 String message;

  HelloResponse({
  this.message = "",

  });

  factory HelloResponse.fromJson(Map<String, dynamic> json) {
    return HelloResponse(
   message: json['message'] as String? ?? "",
    );
  }

  @override
  Map<String, dynamic> toJson() {
    return {
      "message": message,
    };
  }
}

